config/routes.rb
CapitalUnderground::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root "static_pages#home"
 	match 'user/albany/:id', to: 'users#albany', :as => :albany_users, via: 'get'
  match 'user/troy/:id',   to: 'users#troy',   :as => :troy_users,   via: 'get'
  match 'user/schen/:id',  to: 'users#schen',  :as => :schen_users,  via: 'get'
  match 'user/cp/:id',  to: 'users#cp',  :as => :cp_users,  via: 'get'
  match '/signup',  to: 'users#new',					 via: 'get'			
  match '/signin',  to: 'sessions#new', 			 via: 'get'
  match '/signout', to: 'sessions#destroy',		 via: 'delete'
  match '/help',    to: 'static_pages#help',   via: 'get'
  match '/about',   to: 'static_pages#about',  via: 'get'
 	match '/first',   to: 'static_pages#first',  via: 'get'
 	

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<p>Created by Chris LaBarge</p>
	</small>
	<!--<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%#= link_to "Sign in", '#' %></li>
		</ul>
	</nav> -->
</footer>

app/views/layouts/_header.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <% if current_page?('/')%>
           	<a class="navbar-brand" href="/">Welcome</a>
          <% elsif current_page?('/signup')%>
          	<a class="navbar-brand" href="/">Capital Underground</a>
          <% elsif current_page?('/help') or current_page?('/about')%> <!--This is for the education thing-->
          	<p class="navbar-brand" href="/">Y</p>
          <%else%>	
           	<a class="navbar-brand" href="/"><p>Cash: $<%=@user.cash%></p></a>
           <%end%>
          </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
             <!-- <li class="active"><a href="#">Link</a></li> -->
              
              
              <% if signed_in? %>
          			<li><%= link_to "Profile", current_user %></li>
              
              
 								             
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inventory <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
               	<li> Cannabis: <%= current_user.weed %> ounces</li>
          			<li class="divider"></li>
          			<li> Mushrooms: <%= current_user.shrooms %> ounces</li>
           			<li class="divider"></li>
           			<li> Molly: <%= current_user.molly %> ounces</li>
           			<li class="divider"></li>
           			<li> Cocaine: <%= current_user.cocaine %> ounces</li>
           			<li class="divider"></li>
           			<li> Crystal Meth: <%= current_user.meth %> ounces</li>
           			<li class="divider"></li>
           			<li> Oxycontin: <%= current_user.oxy %> ounces</li>
                
                <!--<li class="divider"></li>
                <li class="dropdown-header">Nav header</li> -->
            
              </ul>
            </li>
          	
          	   <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Travel <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
               	<li><%= link_to "Albany", albany_users_path(current_user) %></li>
          			<li class="divider"></li>
          			<li><%= link_to "Troy", troy_users_path(current_user) %></li>
           			<li class="divider"></li>
           			<li><%= link_to "Schenectady", schen_users_path(current_user) %></li>
           			<li class="divider"></li>
           			<li><%= link_to "Clifton Park", cp_users_path(current_user) %></li>
           		
           		
                
                <!--<li class="divider"></li>
                <li class="dropdown-header">Nav header</li> -->
            
              </ul>
            </li>
          		<li><%= link_to "Sign out", signout_path, method: "delete" %>
          	<% else %>
							<li><%= link_to "Sign in", '/signin' %></li>
          	<% end %>
          </ul>
            
           
          		
          		<!--<ul class="nav navbar-nav navbar-right">
    					  
    					  <% if signed_in? %>
    						<% if current_user.switch == 'albany'%>
          				 <li><%= link_to "Troy", troy_users_path(current_user) %></li>
           			<% elsif current_user.switch == 'profile'%>	
          				<li><%= link_to "Troy", troy_users_path(current_user) %></li>
           				<li><%= link_to "Albany", albany_users_path(current_user) %></li>
           			<% elsif current_user.switch == 'troy'%>	
          				<li><%= link_to "Albany", albany_users_path(current_user) %></li>
            		<%end%>
						    <li><%= link_to "Schenectady", schen_users_path(current_user) %></li>
						  	<li><%= link_to "Sign out", signout_path, method: "delete" %>
              </ul>
						<% else %>
							<li><%= link_to "Sign in", '/signin' %></li>
							
						<% end %> -->
          
          </div><!--/.nav-collapse -->
        </div>
      </div>





    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>



    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="animate.min.css">
    
    
   

    
    
    
  </head>
  
  <body>
 		 <%if current_page?('/help') or current_page?('/about') or current_page?('/first')%>
 		 		<%nil%>
 		 <%else%>
 		 		<%= render 'layouts/header' %>
    	<%end%>
    <div class="container">
      
      <% flash.each do |key, value| %>
      	<div class="alert alert-<%= key %>"><%= value %></div>
      <%end%>
      <%= yield %>
    	<%= render 'layouts/footer' %>
    
    </div>
   
 

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
  
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  	
 <!-- 	<script src="//cdn.jsdelivr.net/jquery.velocity/0.8.0/jquery.velocity.min.js"></script> -->

		
		
		<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="smileModal" data-backdrop="static" >
  <div class="modal-dialog modal-sm">
    <div class="modal-content text-center">
      <%=image_tag("http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Smiley.svg/1024px-Smiley.svg.png", height:'200px', width:'200px', id:'smiley')%>
    	<button type="button" class="btn btn-primary btn-lg" id="next">Next Level</button>
    </div>
  </div>
</div> 
		
		
		<script>
			$(document).ready(function(){
  		
  		  var currentButton = 0
  		  
  		  $(".butt").click(function(){
        	$(this).button('loading').delay(1000).queue(function() {
            $(this).button('reset');
            $(this).dequeue();
        	});        
    		});
  		  
  		 
  	$(".correct").click(function(){
   		 
   		 currentButton = currentButton + 1
   		 
   		 if (currentButton == 1) { 
   		  	
   		  	$("#star1").velocity("transition.bounceRightIn",700 );
  				$("#star1").velocity("callout.shake",600);
  		   
  		    if (<%=@level%> == 1) { 
  		  		setTimeout(function() {
						$('#smileModal').modal('show')
  					$("#smiley").velocity("callout.bounce",1450)
  					}, 1350);	
  		  		
  		    }
  		  
  		  }
  			
		  if (currentButton == 2) {
		  	
		  		$("#star2").velocity("transition.bounceRightIn",700 );
  				$("#star2").velocity("callout.shake",600);
		  	
		  	
		  	  if (<%=@level%> == 2) { 
  		  		setTimeout(function() {
						$('#smileModal').modal('show')
  					$("#smiley").velocity("callout.bounce",1450)
  					}, 1350);	
  		  
  		    }
		  	
		  	
		  	}		
  				
  		
  		if (currentButton == 3) {
		  	
		  		$("#star3").velocity("transition.bounceRightIn",700 );
  				$("#star3").velocity("callout.shake",600);
		  	
		  	  if (<%=@level%> == 3) { 
  		  		setTimeout(function() {
						$('#smileModal').modal('show')
  					$("#smiley").velocity("callout.bounce",1450)
  					}, 1350);	
  		    	
     		
     				
  		    }
		  	
		  	
		  	}		
  		});			
  	
     $("#next").click(function(){
	  	$("#smiley").velocity("callout.bounce",800);
	    
	  setTimeout(function() {
	    window.location.replace("/<%=level%>");
			}, 500);
	  
	  });
    
   
   
   

});
		</script>

		




<script>
window.addEventListener('load', function() {
    FastClick.attach(document.body);
}, false);
</script>





<!--   This is for the letter game page...it works but probably isnt as fast
 				as it can be because it uses css animation 
 				
 				the delay is for the stop reset thing to wait a second
-->  

 

  
  
  </body>
</html>